name: "units-test"
on:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  # unit tests
  install-main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install Actions Workspace
        run: npm ci
      - name: Install Test Workspace
        run: cd test-workspace && npm ci
      - name: Unit Tests
        run: npm test


  # test action works running from the graph
  action-test:
    runs-on: ubuntu-latest
    needs:
      - install-main
    steps:
      - uses: actions/checkout@v2
      - name: Install Actions Workspace
        run: npm ci
      - name: Install Test Workspace
        run: cd test-workspace && npm ci
      - uses: ./
        with:
          dryrun: 'true'
