name: "Keep-A-Changelog Tests"
on:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  # unit tests
  unit-test:
    name: "Unit Tests"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install Actions Workspace
        run: npm ci
      - name: Install Test Workspace
        run: cd test-workspace && npm ci
      - name: Unit Tests
        run: npm test


  # test action works running from the graph
  action-test:
    name: "Action Tests"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Actions Workspace
        run: npm ci
      - name: Install Test Workspace
        run: cd test-workspace && npm ci
      - name: Create Diff
        run: |
          echo -e "// New Comment\nexport * from './lib/test-lib-1';" > ./test-workspace/packages/test-lib-1/src/index.ts
          git config user.email "test@test" && git config user.name "Test"
          git add . && git commit -m "Add test lib"
      - name: Run Action
        uses: ./
        with:
          rootdir: "test-workspace"
          dryrun: 'true'
      - name: Cleanup
        run: |
          git reset HEAD~1 --soft && git reset HEAD --hard
